### ISSUE TITLE
2021/04-weekly-report-2021-08/

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/blog#111]
# 2021-08: 尝试写公开周报

An infrastructure engineer, focused on distributed storage system

[https://xuanwo.io/2021/04-weekly-report-2021-08/](https://xuanwo.io/2021/04-weekly-report-2021-08/)

**Comment by Xuanwo** [comment]
Self hosted comment test

**Comment by Allianzcortex** [comment]
cc
