### ISSUE TITLE
Hugo 基于 DocSearch 实现全文搜索

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/blog#121]
https://xuanwo.io/2021/02-docsearch-on-blog/ 

 An infrastructure engineer, focused on distributed storage system

**Comment by tianheg** [comment]
docsearch frontend **only works** with indices generated with the [docsearch crawler](https://github.com/algolia/docsearch-scraper). If you want to build a autocomplete dropdown you should use [autocomplete.js](https://xuanwo.io/2021/02-docsearch-on-blog/github.com/algolia/autocomplete.js) instead, which allow to build autocomplete dropdown on top of any indices.

这段里，autocomplete.js 的链接有问题
